# Map Abbreviations to their full state names. 
states = dict(
    AL="Alabama",
    AK="Alaska",
    AS="American Samoa",
    AZ="Arizona",
    AR="Arkansas",
    AA="Armed Forces Americas",
    AP="Armed Forces Pacific",
    AE="Armed Forces Others",
    CA="California",
    CO="Colorado",
    CT="Connecticut",
    DE="Delaware",
    DC="District Of Columbia",
    FL="Florida",
    GA="Georgia",
    GU="Guam",
    HI="Hawaii",
    ID="Idaho",
    IL="Illinois",
    IN="Indiana",
    IA="Iowa",
    KS="Kansas",
    KY="Kentucky",
    LA="Louisiana",
    ME="Maine",
    MD="Maryland",
    MA="Massachusetts",
    MI="Michigan",
    MN="Minnesota",
    MS="Mississippi",
    MO="Missouri",
    MT="Montana",
    NE="Nebraska",
    NV="Nevada",
    NH="New Hampshire",
    NJ="New Jersey",
    NM="New Mexico",
    NY="New York",
    NC="North Carolina",
    ND="North Dakota",
    MP="Northern Mariana Islands",
    OH="Ohio",
    OK="Oklahoma",
    OR="Oregon",
    PA="Pennsylvania",
    PR="Puerto Rico",
    RI="Rhode Island",
    SC="South Carolina",
    SD="South Dakota",
    TN="Tennessee",
    TX="Texas",
    UM="United States Minor Outlying Islands",
    UT="Utah",
    VT="Vermont",
    VA="Virginia",
    VI="Virgin Islands",
    WA="Washington",
    WV="West Virginia",
    WI="Wisconsin",
    WY="Wyoming")

# A dict that maps state names and their abbreviations to valid synonyms. For
# example, synonyms['IN'] and synonyms['Indiana'] both return ['IN',
# 'Indiana'].
synonyms = dict([(key, [key, value]) for key, value in states.items()] +
                [(value, [key, value]) for key, value in states.items()])
