from seo.tests.test_import_jobs import *
from seo.tests.test_middleware import *
from seo.tests.test_models import *
from seo.tests.test_sitemap import *
from seo.tests.test_views import *
from seo.tests.test_xmlparse import *
from seo.tests.test_helpers import *
from seo.tests.test_admin import *
from seo.tests.test_integration import *
from seo.tests.test_seo_extras import *
from seo.tests.test_cache import *
from seo.tests.test_signals import *
from seo.tests.test_filters import *
from seo.tests.test_local_cache import *
from seo.tests.test_updates import *
from seo.tests.test_transform import *
