from settings import *
facet_counts=({
    "state_slab": [('indiana/usa/jobs::Indiana',1),
                   ('new-jersey/usa/jobs::New Jersey',2),
                   ('new-york/usa/jobs::New York',3),
                   ('none/ita/jobs::None',4),
                   ('none/irl/jobs::None',5),
                   ('none/nrw/jobs::None',6),
                   ('kentucky/usa/jobs::Kentucky',10),
                   ('california/usa/jobs::California',11),
                   ('nevada/usa/jobs::Nevada',12),
                   ('none/saf/jobs::None',13),
                   ('north-carolina/usa/jobs::North Carolina',14),
                   ('none/mex/jobs::None',15),
                   ('none/can/jobs::None',16),
                   ('south-carolina/usa/jobs::South Carolina',17),
                   ('west-carolina/usa/jobs::West Carolina',17),
                   ('east-carolina/usa/jobs::East Carolina',17),
                   ('west-carolina/usa/jobs::West Carolina',17),
                   ('east-carolina/usa/jobs::East Carolina',17)],
    "city_slab": [('newark/new-jersey/usa/jobs::Newark, NJ',1),
                  ('gary/indiana/usa/jobs::Gary, IN',2)],
    "country_slab": [('usa/jobs::USA',1),('can/jobs::Canada',2)],
    "title_slab": [('senior-internal-auditor-jobs/new-jobs::Job 1',1),
                   ('cash-analyst-jobs/new-jobs::Job 2',2)],
     "company_slab": [('ibm/careers::IBM',1),
                      ('providence/careers::Prvovidence',2)],
    "moc_slab": [],
    "mapped_moc_slab": []
    },{
    "state_slab": [('indiana/usa/jobs::Indiana',1),
                   ('new-jersey/usa/jobs::New Jersey',2),
                   ('new-york/usa/jobs::New York',3),
                   ('none/ita/jobs::None',4),
                   ('none/irl/jobs::None',5),
                   ('none/nrw/jobs::None',6),
                   ('kentucky/usa/jobs::Kentucky',10),
                   ('california/usa/jobs::California',11),
                   ('nevada/usa/jobs::Nevada',12),                   
                   ('none/nrw/jobs::None',6),
                   ('none/nrw/jobs::None',6),
                   ('none/nrw/jobs::None',6),
                   ('none/nrw/jobs::None',6),
                   ('none/nrw/jobs::None',6),
                   ('none/nrw/jobs::None',6),
                   ('none/saf/jobs::None',13)],
    "city_slab": [('newark/new-jersey/usa/jobs::Newark, NJ',1),
                  ('gary/indiana/usa/jobs::Gary, IN',2)],
    "country_slab": [('usa/jobs::USA',1),('can/jobs::Canada',2)],
    "title_slab": [('senior-internal-auditor-jobs/new-jobs::Job 1',1),
                   ('cash-analyst-jobs/new-jobs::Job 2',2)],
     "company_slab": [('ibm/careers::IBM',1),
                      ('providence/careers::Prvovidence',2)],
    "moc_slab": [],
    "mapped_moc_slab": []
    })
